blank_issues_enabled: false
contact_links:
  - name: 🤔 Questions and Help
    url: https://plantemoran.service-now.com/
    about: This issue tracker is not for support questions. Please contact the Plante Moran help desk for support.
